### ISSUE TITLE
A new idea about unlock FovScale.

### ISSUE THREAD

**Issue by PhDreamX** [PierroD/Market#1]
The tool can unlock the Fov and FPS,nice work!
By the way,I think it would be a good idea if the tool can unlock the FovScale,which affects the graphic when aimming down sights in the game.
Some dedicated servers like IW4X and Plutonium,both support this function.But Steam edition can not do this....
And just one more question,will this tool support COD4,WaW,BO,BO2 and more classic CODs in the future?
Thanks again!

**Comment by PierroD** [comment]
I would be able to add it, and also I could make it work for other cod as well but I don't know if it will be that useful

**Comment by llocousc** [comment]
> I would be able to add it, and also I could make it work for other cod as well but I don't know if it will be that useful

I would love to have this for BO1 and CoD4 Remastered that would be AMAZING, thx for you amazing job.

**Comment by PhDreamX** [comment]
Great!

**Comment by Valeri-afk** [comment]
hello, i recently installed fps unlocker for MW2 and it works fine, but im interesting how it works? as i know mw2 using IW engine which is written in C++, but u programm is written in C#, so it cofused me. I heard about dll injection before, but im newbie at this at all. Could u give me advice or a tip in these subject?
