### ISSUE TITLE
[Idea]How about SafeArea option?

### ISSUE THREAD

**Issue by PhDreamX** [PierroD/Market#10]
Here's the configs:
safeArea_vertical "1"
safeArea_horizontal "1"
safeArea_adjusted_vertical "1" 
safeArea_adjusted_horizontal "1" 

These codes can change the Hud/UI in actual game more like console version such as Xbox 360. 
And the dedicated servers like IW4X also provided this feature before,just like this picture I upload. 
I have tried the External Console in the Market,but it's a shame that the configs didn't work...
![20220721152901_1](https://github.com/PierroD/Market/assets/87532176/77e72147-c1cb-44d7-883d-26d257eba73d)

Looking forward to add this feature to the Market,appreciate!

**Comment by PierroD** [comment]
Just to answer after closing this request, it's not the ExternalConsole fault, 
The correct dvars are (at least on MW3  M-P, not tested on MW2 but it should be the same) : 
- profileMenuOption_safeAreaHorz
- profileMenuOption_safeAreaVert

> The dvars you were using only move the settings SafeArea (which is dumb I know)
