### ISSUE TITLE
FPS & FOV UNLOCKER COD4 REMASTERED

### ISSUE THREAD

**Issue by llocousc** [PierroD/Market#2]
I would love to have this for CoD4 Remastered that would be AMAZING, thx for you amazing job.

**Comment by PhDreamX** [comment]
same

**Comment by PierroD** [comment]
unfortunately CoD4 Remastered is running on a 64bit engine, and I only deal with the old one which is running on a 32bit engine (from WaW to BO2)

**Comment by llocousc** [comment]
> unfortunately CoD4 Remastered is running on a 64bit engine, and I only deal with the old one which is running on a 32bit engine (from WaW to BO2)

what a shame, and there is no more ways to do it? i remember using fps unlocker when the game was released :S

**Comment by PierroD** [comment]
@llocousc if you really want one, because as I understand it's a shame that I can't give you what you want, go make it yourself :wink:

**Comment by llocousc** [comment]
> @llocousc if you really want one, because as I understand it's a shame that I can't give you what you want, go make it yourself 😉

i wish i knew how to do one...
