### ISSUE TITLE
Error when updating the app

### ISSUE THREAD

**Issue by GKid94** [PierroD/Market#3]
App shows an error when installing update, and also add a auto update popup when you open the app
![Screenshot 2023-10-22 194315](https://github.com/PierroD/Market/assets/18757054/f4ff9f16-648a-46a7-91cf-ee7d9e586ace)

**Comment by PierroD** [comment]
Thank you for your feedback I will look into it

**Comment by PierroD** [comment]
I fix it, but it's not possible for the updater to update himself, so please download the latest version here : [Download 2.1.3](https://raw.githubusercontent.com/PierroD/Market/main/_updates/Market%20v2.1.3.zip)

**Comment by GKid94** [comment]
Isn't 2.4.9 the latest one?
