### ISSUE TITLE
Add contact info

### ISSUE THREAD

**Issue by GKid94** [PierroD/Market#4]
Add contact info in the launcher, and what does the movie option mean in the MW2 options menu?
![Screenshot 2023-10-25 211508](https://github.com/PierroD/Market/assets/18757054/b790d649-cad3-4c18-9790-0a1b2ed51d7c)

**Comment by PierroD** [comment]
the movie doesn't actually exist in the MW2 settings, it refers to a console command name r_filmUseTweaks which make your game look more colorfull, I don't see the point about the contact infos, what would you like me to add ?

**Comment by GKid94** [comment]
> the movie doesn't actually exist in the MW2 settings, it refers to a console command name r_filmUseTweaks which make your game look more colorfull, I don't see the point about the contact infos, what would you like me to add ?

Ok thanks, well you can add the social and support links like Github, Facebook, YouTube, Instagram, Tik Tok and so on for people to contact you and report problems
![Screenshot 2023-10-26 192012](https://github.com/PierroD/Market/assets/18757054/7e2439f6-3d40-4a12-8c81-f15a06e3c0f4)

**Comment by GKid94** [comment]
@PierroD Can you change the Movie option name to Movie effect to be more understandable? and also add info about each option
