### ISSUE TITLE
add “cg_fovmin” 

### ISSUE THREAD

**Issue by 1931129016** [PierroD/Market#5]
hope the author can add this parameter

**Comment by PierroD** [comment]
why would it be usefull if you already can change your default fov ?

**Comment by 1931129016** [comment]
![屏幕截图 2023-11-02 190726](https://github.com/PierroD/Market/assets/42986213/4970e52c-8803-478c-b0a7-55bcff3fb65d)
Weapons gain better visibility when aimed 
I have been using your tools since this version I am your loyal user
If possible, please copy back “Rage Vars”

**Comment by PierroD** [comment]
Okay I see the point here I see if i add it or not, and for the "Rage vars" which is the true mw2 fullbright, I might not put it back to the game.

**Comment by 1931129016** [comment]
Thank you.

Looking forward to the new version
